package com.weeklyreport.activity;

public enum ActivityType {

    REPORT_CREATED,
    REPORT_SUBMITTED,
    REPORT_RESUBMITTED,
    REPORT_CHANGES_REQUESTED,
    REPORT_APPROVED,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_ARCHIVED,

    PROJECT_MEMBER_ASSIGNED,
    PROJECT_MEMBER_REMOVED,

    MANAGER_ASSIGNED,

    USER_ROLE_CHANGED,
    USER_ACTIVATED,
    USER_DEACTIVATED
}