package com.weeklyreport.activity;

public enum ActivityType {

    REPORT_CREATED,
    REPORT_SUBMITTED,
    REPORT_RESUBMITTED,
    REPORT_CHANGES_REQUESTED,
    REPORT_APPROVED,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_ARCHIVED,
    PROJECT_ACTIVATED,
    PROJECT_DELETED,

    PROJECT_MEMBER_ASSIGNED,
    PROJECT_MEMBER_REMOVED,

    MANAGER_ASSIGNED,
    MANAGER_REMOVED,

    USER_INVITED,
    INVITATION_ACCEPTED,
    USER_ROLE_CHANGED,
    USER_ACTIVATED,
    USER_DEACTIVATED
}
